### PR TITLE
chore(deps): update gts dependency

### PR DESCRIPTION
**Pull request by bcoe**

### CODE REVIEW

**Comment by callmehiphop** [comment]
@bcoe all this code is generated right? I'm not sure what is actionable for us to do here.

**Comment by alexander-fenster** [comment]
Seems like my `ts-ignore`s are not working after being moved by `gts fix` :(  Trying to figure out how to deal with it.

**Comment by alexander-fenster** [comment]
@bcoe All fixed now!

**Comment by bcoe** [comment]
@alexander-fenster thank you :tada:

**Pull request merged**
